# Generated by Django 3.1.5 on 2021-01-26 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Priority', models.IntegerField()),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
